### ISSUE TITLE
update angular dependencies

### ISSUE THREAD

**Issue by amitport** [DesertFoxNV/ngx-autosize-input#1]
this lib seems to work fine with `angular@5` and `zone.js@0.8` but prints warning because it has dependencies on `angular@2` and `zone.js@0.7`.

Could you update those to support to entire range? (something like `>=2.4.0 <6`)

Thank you! great work BTW

**Comment by joshuawwright** [comment]
As requested I have changed to the dependencies to include a range:
"@angular/core": ">=2.4.0",
    "zone.js": ">=0.7.2"

See Commit:
[7731b4f]

Published NPM version: 1.0.2
