### ISSUE TITLE
If input is disabled (only for display), avoid setWidth in ngOnChanges

### ISSUE THREAD

**Issue by bthieblot** [DesertFoxNV/ngx-autosize-input#12]
Hi,

I think it's the last one, but for example I want to use your package to adjust width for input that are disabled (only for displaying information). So, they never changed and we shouldn't update the width in the OnChanges cycle !

Tell me ;)

**Comment by joshuawwright** [comment]
Agreed, I will look into this.

**Comment by joshuawwright** [comment]
i will add this soon

**Comment by joshuawwright** [comment]
I have removed ngOnChanges, as it doesn't appear to be needed.
