### ISSUE TITLE
AoT fails on angular 8

### ISSUE THREAD

**Issue by HollyLiang** [DesertFoxNV/ngx-autosize-input#13]
Hello

I update my project to Angular 8 and ng-autosize-input version 2.2.2 fails on `ng build --prod` with AoT.
The error message is 'Directive AutoSizeInputDirective, Expected 0 arguments, but got 1.'
I'm not sure that problem is in `auto-size-input.directive.ts` line 19?

**Comment by joshuawwright** [comment]
this should now be resolved in 2.3
