### ISSUE TITLE
AutoResize not working properly on Firefox/Edge/IE11

### ISSUE THREAD

**Issue by ryankempster** [DesertFoxNV/ngx-autosize-input#14]
Angular 8
ngx-autosize-input 2.3.4

Tested with:
Chrome Version 76.0.3809.132 (Official Build) (64-bit)
Firefox 69.0 (64-bit)
Edge 38.14393.2068.0
IE  11.2906

Just using a simple input:
```
    <input AutoSizeInput>

```
It doesn't resize the correct amount and makes the text overflow on the left-side of the input field. Can be reproduced in Firefox/Edge/IE but works properly in Chrome.

![image](https://user-images.githubusercontent.com/5795322/64851517-70fd1b00-d60f-11e9-8651-0ae2b02ee35a.png)

**Comment by pitman69** [comment]
I've opened a pull request to demonstrate a cross-browser fix for resizing. Problem seems to be in how it determines the font to use for creating text metrics.
https://github.com/DesertFoxNV/ngx-autosize-input/pull/15

**Comment by bmtheo** [comment]
Hey just jumping in to say that @pitman69 solution almost works for my case

In Edge I had to add 2 pixels make it work correctly (I don't know why)

I'm also interested with a proper fix for this issue

My workaround code :



```
    isIE = false;
    isEdge = false;

    constructor(private element: ElementRef, private renderer: Renderer2) {
        // Internet Explorer 6-11
        this.isIE = !!document['DOCUMENT'];

        // Edge 20+
        this.isEdge = !this.isIE && !!window['StyleMedia'];
    }
```


```
    setWidth(width: number): void {
        if (this.isEdge) {
            width = width + 2;
        }
        const element = this.element.nativeElement;
        const parent = this.renderer.parentNode(element);
        this.setParentWidth ? this.renderer.setStyle(parent, 'width', width + 'px')
            : this.renderer.setStyle(element, 'width', width + 'px');
    }
```

**Comment by joshuawwright** [comment]
Awesome I will take a look at this ASAP.

**Comment by joshuawwright** [comment]
@pitman69  and @bmtheo I have merged in your changes. Thanks for putting in a PR!
