### ISSUE TITLE
angular 9 warning

### ISSUE THREAD

**Issue by canbax** [DesertFoxNV/ngx-autosize-input#17]
It seems like it is working fine with angular 9 and angular 8 as well. But When I make `npm install` I see a warning 

> npm WARN ngx-autosize-input@2.3.7 requires a peer of @angular/common@^8.2.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-autosize-input@2.3.7 requires a peer of @angular/core@^8.2.0 but none is installed. You must install peer dependencies yourself.

Thanks for this useful package

**Comment by joshuawwright** [comment]
Thanks for bringing this to my attention. I will see what can be done.

**Comment by joshuawwright** [comment]
@canbax This should now be solved in Angular 10+. The peer dependencies will now align with the angular version and major version of this package.
