### ISSUE TITLE
Set minimum width to accommodate placeholder text

### ISSUE THREAD

**Issue by thatisuday** [DesertFoxNV/ngx-autosize-input#2]
Currently, placeholder text is not fully shown as width of input is less than placeholder text. Is there any way to do this?

**Comment by joshuawwright** [comment]
@thatisuday I can definitely add this functionality. I have a few question:

1) Will the placeholder text represent the minimum width. For instance if a user types in some text, then erases it all, would you like the input box to become no smaller than the original placeholder text?

**Comment by thatisuday** [comment]
I think it should be in the configuration whether to keep placeholder text
as min width.

**Comment by joshuawwright** [comment]
@thatisuday 

Proposed solution:

Create a new parameter to control the minimum width (minWidth), where minWidth is the width of a single underscore character calculated from the input font and size. This way you can set the min width, regardless of whether or not you have a placeholder.

_Enhancement 1_
<input appAutoSizeInput [minWidth]="4">

Then one solution to the problem would be something like:
<input placeholder="Example" appAutoSizeInput [minWidth]="7" >

In this example, minWidth is set to 7, as the placeholder text ("Example"), is 7 characters long.

Another way to achieve the desired behavior using feature 1, would be to store the place holder text in your component typescript file:

Component Typescript File
`public placeHolderText = "Example"`

Corresponding HTML File
`<input [placeholder]="placeHolderText" appAutoSizeInput [minWidth]="placeHolderText.length" >

In this example, you don't have to enter a number for the minWidth parameter as it is determined automatically using the .length property.

Another option would be the addition of a new parameter, usePlaceHolderText, which will be a boolean. If usePlaceHolderText is true it will set the minimum width to the placeholder text.

_Feature 2_
`<input placeholder="placeHolderText" appAutoSizeInput [usePlaceHolderText]="true" >`

I am thinking I will definitely add feature 1. But am unsure about feature 2, as it can be achieved using feature 1. The only advantage I see with feature 2 is that the html markup is less verbose. Thoughts?

**Comment by joshuawwright** [comment]
@thatisuday I have added the requested features in version 2.0.0
