### ISSUE TITLE
Does not auto resize with OnPush

### ISSUE THREAD

**Issue by nartc** [DesertFoxNV/ngx-autosize-input#25]
Thanks for the library. However, I run into an issue with OnPush change detection. Check out the following Stackblitz: https://stackblitz.com/edit/ngx-autosize-input-copqbe

**Comment by joshuawwright** [comment]
This has been solved in the latest version. Note that version 10 requires Angular 10, and that the selector has changed from `AutoSizeInput` to `autoSizeInput`

**Comment by nartc** [comment]
@DesertFoxNV It doesn't seem to work. https://stackblitz.com/edit/ngx-autosize-input-10-dvbbj6?file=src%2Fapp%2Fapp.component.html 
I tried binding the `name` property with `ngModel` and the input isn't "autosized" until focus then blur.

**Comment by joshuawwright** [comment]
@nartc 

OK, I added the needed check, it should now work with OnPush in version (10.0.4): 
https://stackblitz.com/edit/ngx-autosize-input-10-f611qu?file=package.json
