### ISSUE TITLE
Mac OS `npm install` gives error

### ISSUE THREAD

**Issue by canbax** [DesertFoxNV/ngx-autosize-input#29]
Hi
My project uses angular 11 This library depends on angular 10. This somehow causes an error.

I just deleted package-lock.json file and node_modules folder.

`npm install` gives an error on Mac OS. It was fine on windows 10.

> # npm resolution error report
> 
> 2021-02-26T13:43:39.342Z
> 
> While resolving: ng-visuall@1.0.0
> Found: @angular/common@11.2.3
> node_modules/@angular/common
>   @angular/common@"^11.1.2" from the root project
> 
> Could not resolve dependency:
> peer @angular/common@"^10.0.0" from ngx-autosize-input@10.0.6
> node_modules/ngx-autosize-input
>   ngx-autosize-input@"^10.0.6" from the root project
> 
> Fix the upstream dependency conflict, or retry
> this command with --force, or --legacy-peer-deps
> to accept an incorrect (and potentially broken) dependency resolution.

My npm version is "7.5.4". My node version is "v10.16.3"

**Comment by joshuawwright** [comment]
Looks like I need to release a version for 11.0.0.

**Comment by canbax** [comment]
I would appreciate it. Lately, npm starts giving weird errors.

**Comment by joshuawwright** [comment]
OK try installing the latest version (11.0.1):
`npm i ngx-autosize-input@latest`

Let me know if it doesn't work.

**Comment by canbax** [comment]
It seems like fixed
