### ISSUE TITLE
Not work on Mozilla Firefox

### ISSUE THREAD

**Issue by Stepan-Demchenko** [DesertFoxNV/ngx-autosize-input#31]
Hi
My project uses angular universal 10. 
In the chrome dynamic width of input is applied from directive, but not on Mozilla Firefox.

**Comment by joshuawwright** [comment]
Can you provide a stack blitz for this issue? I am not familiar with Angular Universal, so it would be difficult for me to emulate the issue.

**Comment by joshuawwright** [comment]
Were you able to get it to work?

**Comment by Stepan-Demchenko** [comment]
@DesertFoxNV  yes, its my fault. 
When I used construction like this 
`<input
    autoSizeInput
    includePadding="false"
    includeBorders="false">
`
it works fine, as expected, in the Chrome and Safari but not in Mozilla FireFox.

After a while, I changed to this construction:
`<input
    autoSizeInput
    [includePadding]="false"
    [includeBorders]="false">
`
and after that it worked in the Mozilla FireFox.
It's amazing that Webkit recognizes string 'false' like type False.

**Comment by joshuawwright** [comment]
Interesting, thanks for information!
