### ISSUE TITLE
Only Include placeholder text if input has no value

### ISSUE THREAD

**Issue by fhawkes** [DesertFoxNV/ngx-autosize-input#32]
Would it be possible to only consider the length of the placeholder for minWidth if there isn't a value in the input.

In the event that a value is smaller than the placeholder input doesn't resize to fit the smaller text. I can create a PR for this if you'd like it seems like a simple change.

**Comment by joshuawwright** [comment]
Seems reasonable to me, ya that would be great if you want to create a PR.

**Comment by fhawkes** [comment]
I'm also fine with making it configurable so that the default behavior remains the way it is. So maybe adding a flag like includePlaceholderEmptyOnly which would default to false. Let me know if you have a better param name.

**Comment by joshuawwright** [comment]
I wonder if you can actually achieve what you want already, one sec I will create a code example.

**Comment by joshuawwright** [comment]
Component:
placeholder = 'my placeholder';
value = '';

Template:
`<input autoSizeInput [placeholder]="placeholder" [includePlaceholder]="!value">`

Here if there isn't a value, the min width is set to the placeholder. If the value exists the min width is set to the value. Is this the right behavior?

The downside of this approach is that it can't be set at the provider level using CUSTOM_AUTO_SIZE_INPUT_OPTIONS. If we want to set it here then I think we will need to add another attribute, maybe named `usePlaceholderWhenEmpty`.

Thoughts?

**Comment by fhawkes** [comment]
So that was my first attempt, but it didn't see like includePlaceholder would update if I added a value and then removed it. It also seemed like it would be slightly exhausting to have to add [includePlaceholder]="!value" to every input.

**Comment by joshuawwright** [comment]
Understandable, seems like it makes sense then to create a PR with a new attribute/param.

**Comment by fhawkes** [comment]
You have an opinion on the attribute name?

**Comment by joshuawwright** [comment]
How about usePlaceHolderWhenEmpty?
