### ISSUE TITLE
Allow for users to use directive with formControlName as well (reactive forms)

### ISSUE THREAD

**Issue by fhawkes** [DesertFoxNV/ngx-autosize-input#34]
I use both reactive and template driven forms in my application and would like to add support for form controls by detecting the ngControl directive as well. It would be identical to the way that we interact with ngModel. I prioritize ngModel of ngControl in the event they are both there.

this will allow users to use formControlName="variable" instead of [ngModel]

**Comment by joshuawwright** [comment]
@fhawkes That sounds great!

**Comment by joshuawwright** [comment]
@fhawkes I published the latest version of the directive with the `usePlaceholderWhenEmpty` feature.

**Comment by fhawkes** [comment]
Thanks I'll hopefully have a PR up tomorrow for ngControl support

**Comment by joshuawwright** [comment]
@fhawkes I have released these new features in 11.0.5. Thanks again for adding some awesome new features!
