### ISSUE TITLE
Adapt for Angular 5

### ISSUE THREAD

**Issue by diegobs2** [DesertFoxNV/ngx-autosize-input#4]
would be good adapt to angular 5 , now dont work

**Comment by joshuawwright** [comment]
@diegobs2 I am able to get it to run on angular 5.0.0 and 5.2.4. What version of angular 5 are you running?

**Comment by DesertFoxNV** [comment]
reference the plunker [](https://plnkr.co/edit/oP9yz3114Z89FVNU1a8z?p=preview)
