### ISSUE TITLE
Bug: usePlaceholderWhenEmpty does not work when includePlaceholder is false

### ISSUE THREAD

**Issue by pc-erin** [DesertFoxNV/ngx-autosize-input#43]
It's currently not possible to get the input field to show the placeholder width when it's empty, but size to the input text when the input text is smaller than the placeholder text.

This seems like it's a bug.

My intended use case is to get the input field to be the length of the placeholder when nothing is entered, then be the length of the input text when there is some (even if the input text is shorter than the placeholder).

Any time you want it to respect the placeholder size, it refuses to get any smaller than the placeholder even when text is entered.

**Comment by joshuawwright** [comment]
@pc-erin Are you using the `usePlaceHolderWhenEmpty` attribute? Like this:

`<input
      autoSizeInput
      placeholder="Should fit to whatever text is displayed"
      [usePlaceHolderWhenEmpty]="true"
      type="text"
    >`

**Comment by pc-erin** [comment]
HAHAHAHA omg I got the capitalization wrong on `usePlaceHolderWhenEmpty`

Thank you!
