### ISSUE TITLE
apply on a parent container

### ISSUE THREAD

**Issue by sdudnic** [DesertFoxNV/ngx-autosize-input#51]
Sometimes we would like to apply the attribute on a parent container. By example, to a third party component that embedds an input, so the input is not available directly to the user. Say, when using 

```
<kendo-textbox
	  size="small"
	  placeholder="Small"
	  [autosize]="???"
	  [clearButton]="true"
>
</kendo-textbox>
```

so, the action to be taken on the fist child input in the DOM

**Comment by joshuawwright** [comment]
@sdudnic Did you try using the attribute setParentWidth?
`[setParentWidth]="true"`

**Comment by sdudnic** [comment]
Where to apply the attribute? On kendo-textbox?

**Comment by joshuawwright** [comment]
Ya try this and let me know if it doesn't work:
autoSizeInput
`
<kendo-textbox
	  size="small"
	  placeholder="Small"
	  autoSizeInput
	  [setParentWidth]="true"
	  [clearButton]="true"
>
</kendo-textbox>
`

**Comment by joshuawwright** [comment]
@sdudnic After looking at Kendo's api, I don't think this directive will work for the textbox-component. You will probably have to create a custom solution. Sorry :(
