### ISSUE TITLE
Cannot resolve 'ngx-autosize-input' since 15.0.1

### ISSUE THREAD

**Issue by ChristianHehlBM** [DesertFoxNV/ngx-autosize-input#59]
I tried updating to 15.0.1 or 15.0.2 but both versions do not seem to work. Looking at the files in the node_modules it seems like something went wrong while publishing.

see for 15.0.2:
https://www.npmjs.com/package/ngx-autosize-input/v/15.0.2?activeTab=code

and for 15.0.0:
https://www.npmjs.com/package/ngx-autosize-input/v/15.0.0?activeTab=code

**Comment by joshuawwright** [comment]
@ChristianHehlBM Thanks for the heads up. I have fixed it!
