### ISSUE TITLE
Update rxjs peer dependency to include minor versions

### ISSUE THREAD

**Issue by cwoebker** [DesertFoxNV/ngx-autosize-input#60]
We have started to use this library with rxjs version 7.7.0 and more recently with 7.8.0 and are not facing any issues.

Similar to the issue #54 I would propose unpinning the rxjs peer dependency like this:

```
"peerDependencies": {
    "@angular/common": "^15.0.0",
    "@angular/core": "^15.0.0",
    "@angular/forms": "15.0.4",
    "rxjs": "^7.5.7"
  },
 ```

**Comment by joshuawwright** [comment]
@cwoebker thanks I will work on this soon

**Comment by joshuawwright** [comment]
@cwoebker done in v 15.0.4
