### ISSUE TITLE
Please, could you release a version for angular 17?

### ISSUE THREAD

**Issue by uzenith360** [DesertFoxNV/ngx-autosize-input#62]
Thanks for your work!
I encountered an npm error while trying to install on angular 17 project.

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: photographers-app-frontend@0.0.0
npm ERR! Found: @angular/common@17.2.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^17.0.9" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^16.0.0" from ngx-autosize-input@16.0.0
npm ERR! node_modules/ngx-autosize-input
npm ERR!   ngx-autosize-input@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by joshuawwright** [comment]
@uzenith360 Done :smile:

**Comment by Hiaslafson** [comment]
No 17 release or? only open PR as I can see?

**Comment by joshuawwright** [comment]
@Hiaslafson version 17 was released, I just forgot to create a release. I just published 17.0.1 which includes a patch for the peer dependencies.
