### ISSUE TITLE
Could you please release a support version for Angular 18

### ISSUE THREAD

**Issue by artfanvikram** [DesertFoxNV/ngx-autosize-input#66]
While upgrading to latest Angular v18, I am getting below error

While resolving: ngx-autosize-input@17.0.1
npm ERR! Found: @angular/common@18.0.4
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^18.0.0 || ^19.0.0" from @angular/cdk@18.0.4
npm ERR!   node_modules/@angular/cdk
npm ERR!     peer @angular/cdk@"18.0.4" from @angular/material@18.0.4
npm ERR!     node_modules/@angular/material
npm ERR!       peer @angular/material@"18.0.4" from @angular/material-moment-adapter@18.0.4
npm ERR!       node_modules/@angular/material-moment-adapter
npm ERR!         @angular/material-moment-adapter@"^18.0.4" from the root project
npm ERR!       1 more (the root project)
npm ERR!     @angular/cdk@"^18.0.4" from the root project
npm ERR!   peer @angular/common@"18.0.4" from @angular/forms@18.0.4
npm ERR!   node_modules/@angular/forms
npm ERR!     peer @angular/forms@"^18.0.0 || ^19.0.0" from @angular/material@18.0.4
npm ERR!     node_modules/@angular/material
npm ERR!       peer @angular/material@"18.0.4" from @angular/material-moment-adapter@18.0.4
npm ERR!       node_modules/@angular/material-moment-adapter
npm ERR!         @angular/material-moment-adapter@"^18.0.4" from the root project
npm ERR!       1 more (the root project)
npm ERR!     peer @angular/forms@">=9.0.0" from ngx-color-picker@12.0.1
npm ERR!     node_modules/ngx-color-picker
npm ERR!       ngx-color-picker@"^12.0.1" from the root project
npm ERR!     1 more (the root project)
npm ERR!   15 more (@angular/material, @angular/platform-browser, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^17.0.0" from ngx-autosize-input@17.0.1
npm ERR! node_modules/ngx-autosize-input
npm ERR!   ngx-autosize-input@"^17.0.1" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@17.3.11
npm ERR! node_modules/@angular/common
npm ERR!   peer @angular/common@"^17.0.0" from ngx-autosize-input@17.0.1
npm ERR!   node_modules/ngx-autosize-input
npm ERR!     ngx-autosize-input@"^17.0.1" from the root project

**Comment by joshuawwright** [comment]
Hi @artfanvikram,

Sorry this took so long. The angular 18 version has been released.

Cheers,
Josh
