### ISSUE TITLE
Angular 18 gives compile errors because of corrupted references in .d.ts files

### ISSUE THREAD

**Issue by jbaan** [DesertFoxNV/ngx-autosize-input#69]
I'm trying to use the 18.0.0 version of ngx-autosize-input, but after npm install I see that the .d.ts files have corrupted reference paths:

For example index.d.ts, (but applies for all other d.ts files as well)

/// <reference path="**index.ngtypecheck.d.ts**" />
export * from './lib/auto-size-input.directive';
export * from './lib/auto-size-input.options';
export * from './lib/auto-size-input.module';
export * from './lib/cdk/cdk-input-auto-size.directive';

**Comment by jbaan** [comment]
/// <reference path="index.ngtypecheck.d.ts" />
export * from './lib/auto-size-input.directive';
export * from './lib/auto-size-input.options';
export * from './lib/auto-size-input.module';
export * from './lib/cdk/cdk-input-auto-size.directive';

**Comment by jbaan** [comment]
I see that references paths are removed when create this issue

![image](https://github.com/user-attachments/assets/4377bf69-96dd-4673-80a0-06ea97655a41)

**Comment by joshuawwright** [comment]
@jbaan I am unable to replicate this issue. If I create an new angular 18 project, then install the library, then add the directive to an input, the directive works as expected. Do you have reproduction steps that I could follow?

**Comment by pdecleer** [comment]
I have the same problem. Strange is that there is a version 18.0.0 on npm, but it does not exists here on github. I have an existing project that I'm upgrading to Angular 18. After updating ngx-autosize-input building fails because of the reference paths

**Comment by vendi95** [comment]
We have the same problem. I think https://github.com/angular/angular/issues/56945 is relevant.
```
"@angular/core": "^18.2.8",
"ngx-autosize-input": "^18.0.0",
"typescript": "5.4.5"

> node -v
v22.10.0
> npm -v
10.9.0
```

**Comment by joshuawwright** [comment]
Thanks everyone for bringing this to my attention. I have upgraded to package to 18.2.9, this should resolve the issue. Let me know if it doesn't and I can re-open.
