### ISSUE TITLE
Issue with implementing editable label. Input doesn't resize when value property bound

### ISSUE THREAD

**Issue by UrKr** [DesertFoxNV/ngx-autosize-input#8]
Hi! 

Thank you for the library.

I'm trying to implement an editable table -- text that turns into an input when clicked.

The issue is that the the input doesn't resize immediately when the label is replaced by the input if the value property is bound. 
[value]="some value" <- doesn't resize
value="just a string literal" <- does resize

https://stackblitz.com/edit/ngx-autosize-input-kyacsf

**Comment by abdatta** [comment]
Try binding with [(ngModel)]. It works.

**Comment by UrKr** [comment]
Hm... yes, ngModel seems to work for the posted example. I have a different one on local machine where it only resizes after I move the mouse. Haven't been able to create a minimal example yet.

**Comment by joshuawwright** [comment]
@UrKr Version 2.2.2 fixes this bug. Binding to [value] or [(ngModel)] should work now.
